/*
 * File: app/view/LockView.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LockView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.lockview',

    requires: [
        'byzCorp.view.LoginViewViewModel1',
        'byzCorp.view.LoginViewViewController1',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'lockview',
    viewModel: {
        type: 'lockview'
    },
    reference: 'lockView',
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            reference: 'lockform',
            itemId: 'lockform',
            bodyStyle: 'background-image:url(resources/images/color.jpg) !important',
            title: 'Oturum Açın',
            titleAlign: 'center',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'form',
                    height: 128,
                    id: 'loginLayout1',
                    margin: '20 40 20 40',
                    width: 325,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            reference: 'lblUserLockInfo',
                            disabled: true,
                            height: 100,
                            id: 'lblUserLockInfo',
                            itemId: 'lblUserLockInfo',
                            margin: '5 5 5 5',
                            text: 'Kullanıcı Adı gelecek'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            inputType: 'password',
                            emptyText: 'Şifre'
                        },
                        {
                            xtype: 'button',
                            id: 'signIn4',
                            margin: '5 5 5 5',
                            ui: 'loginGreen-small',
                            iconAlign: 'right',
                            iconCls: 'x-fa fa-angle-right',
                            text: 'Giriş Yap',
                            listeners: {
                                click: 'onSignInClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'signIn6',
                            margin: '5 5 10 5',
                            ui: 'notRed-small',
                            iconAlign: 'right',
                            iconCls: 'fa fa-sign-out',
                            text: 'Çıkış',
                            listeners: {
                                click: 'onSignInClick21'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});