/*
 * File: app/view/LoginViewViewController1.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LoginViewViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.lockview',

    onSignInLockViewClick: function(button, e, eOpts) {
        debugger;
        var refs = this.getReferences();
        var destroylockview =this.view;
        Ext.Ajax.request({
            url:'/byzCorp/user/getUser',
            params : {
                userName : refs.lblUserIdLock.text,
                password : refs.lockViewPassword.getValue()
            },
            success : function(res){debugger;
                var api = Ext.decode(res.responseText);
                if(api.length>1){
                    if(api[1].success){debugger;
                        var userName = refs.lblUserIdLock.text;
                        var password = refs.lockViewPassword.getValue();

                        if(api[0].USERNAME === userName){debugger;
                            if(api[0].USERPASSWORD === password){
                                refs.lockform.destroy();
                                //destroyLockview.destroy();
                                var mainview = Ext.create('widget.mainview');
                                var mainRefs =mainview.getReferences();
                                var lblGet = mainview.getReferences().lblUserInfo;
                                var lblGetUserId = mainview.getReferences().lblUserId;
                                var lblNewValue = api[0].USERFIRSTNAME + ' '+ api[0].USERLASTNAME+ ' / '+api[0].USERTITLE;
                                var lblUserIdNewValue = api[0].USERID;
                                lblGet.setText(lblNewValue);
                                lblGetUserId.setText(lblUserIdNewValue);
                                if(api[0].USERROLEID===2){
                                    mainRefs.menuStudents.hide();
                                    mainRefs.menuSettings.hide();
                                    mainRefs.menuInternShips.hide();
                                    mainRefs.internShipResponsePanel.hide();
                                }
                                if(api[0].USERROLEID===1){
                                    mainRefs.menuInternShipRequest.hide();
                                }
                            }else{
                                Ext.Msg.alert('Uyarı', 'Hatalı şifre girdiniz.');
                            }

                        }else{
                            Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı girdiniz.');
                        }
                    }else{
                        Ext.Msg.alert('Uyarı', 'Veri tabanında kayıt bulunamadı.');
                    }
                }else{
                    Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı veya şifre girdiniz.');

                }

            }
        });
    },

    onSignOutLockViewClick: function(button, e, eOpts) {
        debugger;
        var refs = this.getReferences();
        var loginview = Ext.create('widget.loginview');
        var destroylockview = this.view;
        refs.lockform.destroy();
        loginview.show();
    }

});
