/*
 * File: app/view/LoginViewViewController1.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LoginViewViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.lockview',

    onSignInClick: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/
        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.lockform.destroy();
    },

    onSignInClick21: function(button, e, eOpts) {
        var refs = this.getReferences();
        var loginview = Ext.create('widget.loginview');
        loginview.show();
        refs.lockform.destroy();
    }

});
