/*
 * File: app/view/LoginViewViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LoginViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginview',

    onSignInClick: function(button, e, eOpts) {
        debugger;
        var refs = this.getReferences();
        var destroyloginView = this.view;
        Ext.Ajax.request({
            url:'/byzCorp/user/getUser',
            params : {
                userName : refs.txtLoginUserName.getValue(),
                password : refs.txtLoginPassword.getValue()
            },
            success : function(res){debugger;
                var api = Ext.decode(res.responseText);
                if(api.length>1){
                    if(api[1].success){
                        var userName = refs.txtLoginUserName.getValue();
                        var password = refs.txtLoginPassword.getValue();

                        if(api[0].USERNAME === userName){debugger;
                            if(api[0].USERPASSWORD === password){
                                //loginView.destroy();
                                refs.loginform.destroy();
                                var mainview = Ext.create('widget.mainview');
                                var mainRefs = mainview.getReferences();
                                var lblGet = mainview.getReferences().lblUserInfo;
                                var lblGetUserId = mainview.getReferences().lblUserId;
                                var lblGetUserName = mainview.getReferences().lblUserName;
                                var lblGetNewValue = api[0].USERFIRSTNAME + ' '+ api[0].USERLASTNAME+ ' / '+api[0].USERTITLE;
                                var lblUserIdNewValue = api[0].USERID;
                                var lblUserNameNewValue = api[0].USERNAME;

                                lblGet.setText(lblGetNewValue);
                                lblGetUserId.setText(lblUserIdNewValue);
                                lblGetUserName.setText(lblUserNameNewValue);
                                if(api[0].USERROLEID===2){
                                    mainRefs.menuStudents.hide();
                                    mainRefs.menuSettings.hide();
                                    mainRefs.menuInternShips.hide();
                                    mainRefs.internShipResponsePanel.hide();
                                }
                                if(api[0].USERROLEID===1){
                                    mainRefs.menuInternShipRequest.hide();
                                }
                            }else{
                                Ext.Msg.alert('Uyarı', 'Hatalı şifre girdiniz.');
                            }

                        }else{
                            Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı girdiniz.');
                        }
                    }else{
                        Ext.Msg.alert('Uyarı', 'Veri tabanında kayıt bulunamadı.');
                    }
                }else{
                    Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı veya şifre girdiniz.');

                }

            }
        });
    },

    onSignInClick2: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/

        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.loginform.destroy();
    },

    onChangePasswordClick: function(button, e, eOpts) {
        debugger;
        var refs = this.getReferences();
        var destroyloginView = this.view;
        Ext.Ajax.request({
            url:'/byzCorp/user/getUser',
            params : {
                userName : refs.txtLoginUserName.getValue(),
                password : refs.txtLoginPassword.getValue()
            },
            success : function(res){debugger;
                var api = Ext.decode(res.responseText);
                if(api.length>1){
                    if(api[1].success){
                        var userName = refs.txtLoginUserName.getValue();
                        var password = refs.txtLoginPassword.getValue();

                        if(api[0].USERNAME === userName){debugger;
                            if(api[0].USERPASSWORD === password){
                                var userId = api[0].USERID;
                                Ext.MessageBox.prompt('Şifre', 'Yeni şifrenizi giriniz:', function(btn, text){
                                    if (btn == 'ok'){
                                        Ext.Ajax.request({
                                            url:'/byzCorp/user/updatePassword',
                                            params : {
                                                password : text,
                                                userId : userId
                                            },
                                            success : function(res){debugger;
                                                var api = Ext.decode(res.responseText);
                                                if(api.success){

                                                    var t = new Ext.ToolTip({
                                                        anchor: 'top',
                                                        anchorToTarget: false,
                                                        //targetXY: [refs.maincontainer.getWidth(), refs.maincontainer.getHeight()],
                                                        title: 'Uyarı',
                                                        html: '0000-Kayıt işlemi başarılı.',
                                                        hideDelay: 200,
                                                        closable: false
                                                    });
                                                    t.show();
                                                }else{
                                                    Ext.Msg.alert('Uyarı', 'Kayıt işlemi gerçekleşmedi.');
                                                }
                                            }
                                        });
                                    }
                                });
                            }else{
                                Ext.Msg.alert('Uyarı', 'Hatalı şifre girdiniz.');
                            }
                        }else{
                            Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı girdiniz.');
                        }

                    }else{
                        Ext.Msg.alert('Uyarı', 'Veri tabanında kayıt bulunamadı.');
                    }
                }else{
                    Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı veya şifre.');
                }
            }
        });

    },

    onSignInClick1: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/

        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.loginform.destroy();
    }

});
