/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "gridColor",
        "xtype": "panel"
    },
    {
        "ui": "loginGreen",
        "xtype": "button"
    },
    {
        "ui": "notRed",
        "xtype": "button"
    },
    {
        "ui": "yellow",
        "xtype": "button"
    }
]);