/*
 * File: app/view/LoginViewViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LoginViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginview',

    onSignInClick: function(button, e, eOpts) {
        var refs = this.getReferences();
        Ext.Ajax.request({
            url:'/user/getUser',
            params : {
                userName : refs.txtLoginUserName.getValue(),
                password : refs.txtLoginPassword.getValue()
            },
            success : function(res){
                var api = Ext.decode(res.responseText);
                if(api[1].success){
                    var userName = refs.txtLoginUserName.getValue();
                    var password = refs.txtLoginPassword.getValue();

                    if(api[0].USERNAME === userName){
                        if(api[0].USERPASSWORD === password){
                            refs.loginform.destroy();
                            var mainview = Ext.create('widget.mainview');
                            var lblGet = mainview.getReferences().lblUserInfo;
                            var lblNewValue = api[0].USERFIRSTNAME + ' '+ api[0].USERLASTNAME+ ' / '+api[0].USERTITLE;
                            lblGet.setText(lblNewValue);
                        }else{
                            Ext.Msg.alert('Uyarı', 'Hatalı şifre girdiniz.');
                        }

                    }else{
                        Ext.Msg.alert('Uyarı', 'Hatalı kullanıcı adı girdiniz.');
                    }
                }else{
                    Ext.Msg.alert('Uyarı', 'Veri tabanında kayıt bulunamadı.');
                }
            }
        });
    },

    onSignInClick2: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/

        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.loginform.destroy();
    },

    onSignInClick21: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/

        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.loginform.destroy();
    },

    onSignInClick1: function(button, e, eOpts) {
        /*debugger;
        var refs = this.getReferences();
        form = button.up('loginform');
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        form.hide();*/

        debugger;
        var refs = this.getReferences();
        var mainview = Ext.create('widget.mainview');
        mainview.show();
        refs.loginform.destroy();
    }

});
