/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.LoginView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.loginview',

    requires: [
        'byzCorp.view.LoginViewViewModel',
        'byzCorp.view.LoginViewViewController',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Checkbox'
    ],

    controller: 'loginview',
    viewModel: {
        type: 'loginview'
    },
    reference: 'loginview',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            reference: 'loginform',
            itemId: 'loginform',
            bodyStyle: 'background-image:url(resources/images/color.jpg) !important',
            title: 'Oturum Açın',
            titleAlign: 'center',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'form',
                    height: 205,
                    id: 'loginLayout',
                    margin: '20 40 20 40',
                    width: 325,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            disabled: true,
                            height: 100,
                            margin: '5 5 5 5',
                            text: 'Hesabınıza giriş yapın'
                        },
                        {
                            xtype: 'textfield',
                            reference: 'txtLoginUserName',
                            id: 'txtLoginUserName',
                            margin: '5 5 5 5',
                            hideLabel: true,
                            emptyText: 'Kullanıcı Adı'
                        },
                        {
                            xtype: 'textfield',
                            reference: 'txtLoginPassword',
                            id: 'txtLoginPassword',
                            margin: '5 5 5 5',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            inputType: 'password',
                            emptyText: 'Şifre'
                        },
                        {
                            xtype: 'button',
                            id: 'signIn',
                            margin: '5 5 5 5',
                            ui: 'loginGreen-small',
                            iconAlign: 'right',
                            iconCls: 'x-fa fa-angle-right',
                            text: 'Giriş Yap',
                            listeners: {
                                click: 'onSignInClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'signIn2',
                            margin: '5 5 5 5',
                            iconAlign: 'right',
                            iconCls: 'fa fa-facebook',
                            text: 'Facebook ile Giriş Yap',
                            listeners: {
                                click: 'onSignInClick2'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'signIn3',
                            margin: '5 5 10 5',
                            ui: 'notRed-small',
                            iconAlign: 'right',
                            iconCls: 'fa fa-question',
                            text: 'Şifremi Unuttum',
                            listeners: {
                                click: 'onSignInClick21'
                            }
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 270,
                    id: 'accountLayout',
                    margin: '20 40 20 40',
                    width: 325,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            disabled: true,
                            height: 100,
                            margin: '5 5 5 5',
                            text: 'Yeni hesap oluşturun'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideLabel: true,
                            emptyText: 'Adı'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideLabel: true,
                            emptyText: 'Soyadı'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            emptyText: 'Kullanıcı Adı'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            inputType: 'email',
                            emptyText: 'Email Adresi'
                        },
                        {
                            xtype: 'textfield',
                            margin: '5 5 5 5',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            inputType: 'password',
                            emptyText: 'Şifre'
                        },
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            margin: '5 5 5 5',
                            boxLabel: 'Şartlar ve koşulları kabul ediyorum'
                        },
                        {
                            xtype: 'button',
                            id: 'signIn1',
                            margin: '5 5 10 5',
                            ui: 'default-toolbar-small',
                            iconAlign: 'right',
                            iconCls: 'x-fa fa-user-plus',
                            text: 'Hesap Oluştur',
                            listeners: {
                                click: 'onSignInClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});