/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'byzCorp.view.MainViewViewModel',
        'byzCorp.view.MainViewViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.button.Split',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.Exporter',
        'Ext.form.Label'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    reference: 'mainview',
    itemId: 'mainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            floatable: false,
            region: 'center',
            reference: 'maincontainer',
            id: 'maincontainer',
            itemId: 'maincontainer',
            layout: 'border',
            header: false,
            iconAlign: 'left',
            iconCls: 'fa fa-bold',
            title: 'byzCorp © v.0.0.1',
            titleAlign: 'left',
            items: [
                {
                    xtype: 'panel',
                    collapseMode: 'header',
                    region: 'west',
                    split: true,
                    border: false,
                    frame: true,
                    itemId: 'menuPanel',
                    margin: '0 0 0 5',
                    collapsed: false,
                    collapseFirst: false,
                    collapsible: true,
                    iconCls: 'fa fa-bars',
                    title: 'Menu',
                    titleCollapse: false,
                    items: [
                        {
                            xtype: 'menu',
                            border: false,
                            floating: false,
                            itemId: 'menu',
                            bodyBorder: false,
                            frameHeader: false,
                            header: false,
                            manageHeight: false,
                            showSeparator: false,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'anaSayfa',
                                    iconCls: 'fa fa-home',
                                    text: 'Ana Sayfa',
                                    tooltip: 'Özet bilgiler ile iş takibinizi kolaylaştırın..',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'ogrenciIslemleri',
                                    iconCls: 'fa fa-graduation-cap',
                                    text: 'Öğrenci İşlemleri',
                                    tooltip: 'Öğrenci kayıt/güncelle/sil işlemlerini tek bir ekrandan kolayca yapın..',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'stajIslemleri',
                                    iconCls: 'fa fa-file',
                                    text: 'Staj İşlemleri',
                                    tooltip: 'Öğrenci staj kayıtlarını oluşturun ve kolayca takip edin..',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'ayarlar',
                                    iconCls: 'fa fa-cog',
                                    text: 'Yönetim İşlemleri',
                                    focusable: true
                                }
                            ],
                            listeners: {
                                click: 'onMenuClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    border: false,
                    itemId: 'contentPanel',
                    margin: '0 5 0 0',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'panel',
                            frame: true,
                            itemId: 'anaSayfaPanel',
                            margin: '',
                            layout: 'accordion',
                            header: false,
                            iconCls: 'fa fa-home',
                            title: 'Ana Sayfa',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'border',
                                    iconCls: 'fa fa-unlock',
                                    title: 'Stajı Devam Eden Öğrenciler'
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'border',
                                    iconCls: 'fa fa-lock',
                                    title: 'Stajı Tamamlanan Öğrenciler'
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'border',
                                    iconCls: 'fa fa-history',
                                    title: 'İşlem Hareketleri'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            border: false,
                            itemId: 'ogrenciIslemleriPanel',
                            layout: 'border',
                            iconCls: 'fa fa-graduation-cap',
                            title: 'Öğrenci İşlemleri',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    border: false,
                                    id: 'ogrencilerGrid',
                                    margin: '5 0 5 0',
                                    bodyBorder: false,
                                    header: false,
                                    title: 'My Grid Panel',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 151,
                                            dataIndex: 'string',
                                            text: 'Öğrenci No'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 151,
                                            dataIndex: 'number',
                                            text: 'T.C. Kimlik No'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 304,
                                            dataIndex: 'date',
                                            text: 'Adı Soyadı'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 297,
                                            dataIndex: 'bool',
                                            text: 'Bölümü'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 280,
                                            dataIndex: 'bool',
                                            text: 'Sınıfı'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 145,
                                            dataIndex: 'bool',
                                            text: 'Aktif Dönem'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    region: 'west',
                                    id: 'ogrKayitContainer',
                                    width: 246,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'form',
                                            region: 'north',
                                            height: 215,
                                            id: 'ogrKayitForm',
                                            margin: '5 5 0 0',
                                            layout: 'form',
                                            bodyPadding: 10,
                                            header: false,
                                            title: 'My Form',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    id: 'ogrNo',
                                                    emptyText: 'Öğrenci No'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'ogrTcKimlikNo',
                                                    emptyText: 'T.C. Kimlik No'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'ogrAdi',
                                                    emptyText: 'Adı'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'ogrSoyadi',
                                                    emptyText: 'Soyadı'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'ogrBolumu',
                                                    emptyText: 'Bölümü'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'ogrSinifi',
                                                    emptyText: 'Sınıfı'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'ogrAktifDonem',
                                                    emptyText: 'Aktif Dönem'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            region: 'center',
                                            margin: '0 5 5 0',
                                            bodyPadding: 10,
                                            header: false,
                                            title: 'My Form',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    margin: '5 5 5 5',
                                                    iconCls: 'fa fa-floppy-o',
                                                    text: 'Kaydet'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    margin: '5 5 5 5',
                                                    iconCls: 'fa fa-trash-o',
                                                    text: 'Sil'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            frame: true,
                            itemId: 'stajIslemleriPanel',
                            layout: 'border',
                            iconCls: 'fa fa-file',
                            title: 'Staj İşlemleri',
                            items: [
                                {
                                    xtype: 'container',
                                    region: 'west',
                                    id: 'stajKayitContainer',
                                    width: 246,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'form',
                                            region: 'north',
                                            height: 188,
                                            id: 'stajKayitForm',
                                            margin: '5 5 0 0',
                                            layout: 'form',
                                            bodyPadding: 10,
                                            header: false,
                                            title: 'My Form',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    id: 'stjOgrenci',
                                                    emptyText: 'Öğrenci'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    id: 'stjBaslangic',
                                                    emptyText: 'Staj Başlangıç Zamanı'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    id: 'stjBitis',
                                                    emptyText: 'Staj Bitiş Zamanı'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'stjDonemi',
                                                    emptyText: 'Staj Dönemi'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'stjTipi',
                                                    emptyText: 'Staj Tipi'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'stjStatu',
                                                    emptyText: 'Statü'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            region: 'center',
                                            margin: '0 5 0 0',
                                            bodyPadding: 10,
                                            header: false,
                                            title: 'My Form',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    margin: '5 5 5 5',
                                                    iconCls: 'fa fa-floppy-o',
                                                    text: 'Kaydet'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    margin: '5 5 5 5',
                                                    iconCls: 'fa fa-trash-o',
                                                    text: 'Sil'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    id: 'stajGrid',
                                    margin: '5 0 0 0',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Öğrenci No'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Adı Soyadı'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Başlangıç Zamanı'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Biriş Zamanı'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Dönemi'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Tipi'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Tamamlandı'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'ayarlarPanel',
                            layout: 'accordion',
                            header: false,
                            iconCls: 'fa fa-cog',
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'kullaniciYonetimi',
                                    layout: 'border',
                                    iconCls: 'fa fa-users',
                                    title: 'Kullanıcı Yönetimi',
                                    items: [
                                        {
                                            xtype: 'container',
                                            region: 'west',
                                            id: 'kullaniciKayitContainer',
                                            width: 246,
                                            layout: 'border',
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    region: 'north',
                                                    reference: 'kullaniciKayitForm',
                                                    height: 215,
                                                    id: 'kullaniciKayitForm',
                                                    margin: '5 5 0 0',
                                                    layout: 'form',
                                                    bodyPadding: 10,
                                                    header: false,
                                                    title: 'My Form',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            reference: 'txtUserId',
                                                            hidden: true,
                                                            id: 'txtUserId',
                                                            emptyText: 'Adı'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            reference: 'txtUserFirstName',
                                                            id: 'txtUserFirstName',
                                                            emptyText: 'Adı'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            reference: 'txtUserLastName',
                                                            id: 'txtUserLastName',
                                                            emptyText: 'Soyadı'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            reference: 'txtUserName',
                                                            id: 'txtUserName',
                                                            emptyText: 'Kullanıcı Adı'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            reference: 'txtUserEmail',
                                                            id: 'txtUserEmail',
                                                            emptyText: 'Email Adresi'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            formBind: true,
                                                            reference: 'cmbUserRole',
                                                            id: 'cmbUserRole',
                                                            emptyText: 'Kullanıcı Rolü',
                                                            autoLoadOnValue: true,
                                                            displayField: 'USERROLENAME',
                                                            minChars: 1,
                                                            store: 'getActiveRoles',
                                                            valueField: 'USERROLEID'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            formBind: true,
                                                            reference: 'cmbUserTitle',
                                                            id: 'cmbUserTitle',
                                                            emptyText: 'Ünvanı',
                                                            autoLoadOnValue: true,
                                                            displayField: 'LOOKUPDETAILNAME',
                                                            minChars: 1,
                                                            store: 'getLookUpDetailUserTtile',
                                                            valueField: 'LOOKUPDETAILVALUE'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            formBind: true,
                                                            reference: 'cmbUserStatus',
                                                            id: 'cmbUserStatus',
                                                            emptyText: 'Aktif',
                                                            autoLoadOnValue: true,
                                                            displayField: 'STATUSNAME',
                                                            minChars: 1,
                                                            store: 'Status',
                                                            valueField: 'STATUSVALUE'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'form',
                                                    region: 'center',
                                                    margin: '0 5 5 0',
                                                    bodyPadding: 10,
                                                    header: false,
                                                    title: '',
                                                    layout: {
                                                        type: 'hbox',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            id: 'kaydet',
                                                            margin: '5 5 5 5',
                                                            iconCls: 'fa fa-floppy-o',
                                                            text: 'Kaydet',
                                                            listeners: {
                                                                click: {
                                                                    fn: 'onKaydetClick',
                                                                    scope: 'controller'
                                                                }
                                                            }
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            id: 'sil',
                                                            margin: '5 5 5 5',
                                                            iconCls: 'fa fa-trash-o',
                                                            text: 'Sil'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            region: 'center',
                                            reference: 'usersGrid',
                                            id: 'UsersGrid',
                                            itemId: 'UsersGrid',
                                            margin: '5 0 5 0',
                                            header: false,
                                            autoLoad: true,
                                            forceFit: true,
                                            store: 'getAllUsers',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    autoRender: true,
                                                    dataIndex: 'USERFIRSTANDLASTNAME',
                                                    exportStyle: {
                                                        format: 'Currency',
                                                        alignment: {
                                                            horizontal: 'Right'
                                                        }
                                                    },
                                                    text: 'Adı Soyadı'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    autoRender: true,
                                                    dataIndex: 'USERNAME',
                                                    text: 'Kullanıcı Adı'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    autoRender: true,
                                                    dataIndex: 'USERTITLE',
                                                    text: 'Ünvanı'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    autoRender: true,
                                                    dataIndex: 'USEREMAIL',
                                                    text: 'Email'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    autoRender: true,
                                                    dataIndex: 'USERROLENAME',
                                                    text: 'Rolü'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    autoRender: true,
                                                    dataIndex: 'USERSTATUSNAME',
                                                    text: 'Statü'
                                                }
                                            ],
                                            viewConfig: {
                                                id: 'userGrid',
                                                itemId: 'userGrid',
                                                listeners: {
                                                    rowclick: {
                                                        fn: 'onUserGridRowClick',
                                                        scope: 'controller'
                                                    }
                                                }
                                            },
                                            dockedItems: [
                                                {
                                                    xtype: 'pagingtoolbar',
                                                    dock: 'bottom',
                                                    id: 'usersGridPaging',
                                                    itemId: 'usersGridPaging',
                                                    displayInfo: true,
                                                    items: [
                                                        {
                                                            xtype: 'splitbutton',
                                                            iconCls: 'fa fa-print',
                                                            text: 'Yazdır',
                                                            menu: {
                                                                xtype: 'menu',
                                                                items: [
                                                                    {
                                                                        xtype: 'menuitem',
                                                                        id: 'excel',
                                                                        iconCls: 'fa fa-file-excel-o',
                                                                        text: 'Excel',
                                                                        listeners: {
                                                                            click: {
                                                                                fn: 'onExcelClick',
                                                                                scope: 'controller'
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    ]
                                                }
                                            ],
                                            selModel: {
                                                selType: 'rowmodel',
                                                mode: 'SINGLE'
                                            },
                                            plugins: [
                                                {
                                                    ptype: 'gridexporter'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    iconCls: 'fa fa-shield',
                                    title: 'Rol Yönetimi'
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'border',
                                    iconCls: 'fa fa-list-ul',
                                    title: 'LookUp Yönetimi',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            region: 'center',
                                            split: false,
                                            reference: 'lookUpGrid',
                                            id: 'lookUpGrid',
                                            itemId: 'lookUpGrid',
                                            margin: '5 0 0 0',
                                            title: 'LookUp Başlıkları',
                                            autoLoad: true,
                                            forceFit: true,
                                            store: 'getActiveLookUps',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    sortable: true,
                                                    dataIndex: 'LOOKUPNAME',
                                                    text: 'Açıklama'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    sortable: true,
                                                    align: 'center',
                                                    dataIndex: 'LOOKUPSTATUS',
                                                    text: 'Statü'
                                                }
                                            ],
                                            viewConfig: {
                                                height: 135
                                            },
                                            dockedItems: [
                                                {
                                                    xtype: 'pagingtoolbar',
                                                    dock: 'bottom',
                                                    width: 360,
                                                    displayInfo: true,
                                                    store: 'getActiveLookUps'
                                                }
                                            ],
                                            listeners: {
                                                rowclick: {
                                                    fn: 'onLookUpGridRowClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            region: 'south',
                                            split: true,
                                            reference: 'lookUpDetailGrid',
                                            height: 180,
                                            margin: '0 0 0 0',
                                            collapsed: true,
                                            collapsible: true,
                                            title: 'LookUp Detayları',
                                            forceFit: true,
                                            store: 'getLookUpDetails',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'LOOKUPDETAILNAME',
                                                    text: 'Açıklama'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    align: 'center',
                                                    dataIndex: 'LOOKUPDETAILVALUE',
                                                    text: 'Değer'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    fixed: true,
                                                    align: 'center',
                                                    dataIndex: 'LOOKUPDETAILSTATUS',
                                                    text: 'Statü'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 44,
                    id: 'upBar',
                    layout: 'border',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'right',
                            id: 'logoutContainer',
                            width: 38,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'logOut',
                                    margin: '5 5 5 5',
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-sign-out',
                                    listeners: {
                                        click: {
                                            fn: 'onLogOutClick',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 33,
                            id: 'userInfoContainer',
                            width: 219,
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    defaultListenerScope: true,
                                    reference: 'lblUserInfo',
                                    autoRender: true,
                                    autoShow: true,
                                    id: 'lblUserInfo',
                                    margin: '5 5 5 5'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'right',
                            height: 33,
                            id: 'araContainer',
                            width: '',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    disabled: true,
                                    id: 'araIcon',
                                    ui: 'plain-toolbar-small',
                                    width: 22,
                                    iconAlign: 'right',
                                    iconCls: 'fa fa-search'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'txtAra',
                                    margin: '5 5 5 0',
                                    width: 350,
                                    inputType: 'search',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true,
                                    listeners: {
                                        keyup: {
                                            fn: 'onTxtAraKeyup',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 23,
                    id: 'downBar',
                    layout: 'border',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 33,
                            id: 'userInfoContainer1',
                            width: 137,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    margin: '5 5 5 5',
                                    text: 'byzCorp © 2017'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});