/*
 * File: app/model/getInternShips.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.model.getInternShips', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'INTERNSHIPSTARTDATE'
        },
        {
            name: 'INTERNSHIPENDDATE'
        },
        {
            name: 'INTERNSHIPID'
        },
        {
            name: 'INTERNSHIPTYPEID'
        },
        {
            name: 'INTERNSHIPSTATUSID'
        },
        {
            name: 'INTERNSHIPPERIODID'
        },
        {
            name: 'INTERNSHIPTYPE'
        },
        {
            name: 'INTERNSHIPSTATUS'
        },
        {
            name: 'INTERNSHIPPERIOD'
        },
        {
            name: 'STUDENTFIRSTANDLASTNAME'
        },
        {
            name: 'INTERNSHIPSTUDENTID'
        },
        {
            name: 'STUDENTNO'
        },
        {
            name: 'INTERNSHIPDAY'
        },
        {
            name: 'INTERNSHIPDONEDAY'
        },
        {
            name: 'INTERNSHIPPLACE'
        },
        {
            name: 'INTERNSHIPDESC'
        },
        {
            name: 'USERTITLEFIRSTANDLASTNAME'
        },
        {
            name: 'INTERNSHIPACCEPTSTATUS'
        }
    ]
});